name 'dmlb2000_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dmlb2000_server'
long_description 'Installs/Configures dmlb2000_server'
version '0.1.2'

depends 'zfs_linux'
depends 'samba'
depends 'dmlb2000_users'
